name: Check
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      CI: true
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup GraalVM CE
      uses: DeLaGuardo/setup-graalvm@3.1
      with:
        graalvm-version: 22.3.0.java11
    - name: Install Native Image
      run: gu install native-image
    - uses: gradle/gradle-command-action@v2
      with:
        arguments: check coveralls --stacktrace --scan
    - name: Show Reports
      uses: actions/upload-artifact@v1
      if: failure()
      with:
         name: reports
         path: build/reports/
